HTTP/1.1 500 Internal Server Error
Content-Type: application/json

{
  "message": "'DexterityTypesControlpanel' object has no attribute 'publishTraverse'",
  "traceback": [
    "File \"/joint/backend/plone.restapi/eggs/Zope-4.1.3-py3.8.egg/ZPublisher/WSGIPublisher.py\", line 156, in transaction_pubevents",
    "    yield",
    "",
    "  File \"/joint/backend/plone.restapi/eggs/Zope-4.1.3-py3.8.egg/ZPublisher/WSGIPublisher.py\", line 338, in publish_module",
    "    response = _publish(request, new_mod_info)",
    "",
    "  File \"/joint/backend/plone.restapi/eggs/Zope-4.1.3-py3.8.egg/ZPublisher/WSGIPublisher.py\", line 248, in publish",
    "    result = mapply(obj,",
    "",
    "  File \"/joint/backend/plone.restapi/eggs/Zope-4.1.3-py3.8.egg/ZPublisher/mapply.py\", line 85, in mapply",
    "    return debug(object, args, context)",
    "",
    "  File \"/joint/backend/plone.restapi/eggs/Zope-4.1.3-py3.8.egg/ZPublisher/WSGIPublisher.py\", line 62, in call_object",
    "    return obj(*args)",
    "",
    "  File \"/joint/backend/plone.restapi/eggs/plone.rest-1.6.0-py3.8.egg/plone/rest/service.py\", line 22, in __call__",
    "    return self.render()",
    "",
    "  File \"/joint/backend/plone.restapi/src/plone/restapi/services/__init__.py\", line 21, in render",
    "    content = self.reply()",
    "",
    "  File \"/joint/backend/plone.restapi/src/plone/restapi/services/controlpanels/get.py\", line 49, in reply",
    "    return self.reply_panel()",
    "",
    "  File \"/joint/backend/plone.restapi/src/plone/restapi/services/controlpanels/get.py\", line 69, in reply_panel",
    "    return IJsonCompatible(panel.get(self.params[1:]))",
    "",
    "  File \"/joint/backend/plone.restapi/src/plone/restapi/controlpanels/types.py\", line 55, in get",
    "    context = context.publishTraverse(self.request, name)"
  ],
  "type": "AttributeError"
}